name: Test build 4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Update core-js
      run: npm install core-js@latest

    - name: Fix Vulnerabilities
      run: npm audit fix

    - name: Fix Linting Issues
      run: npx eslint --fix ./src/index.js

    - name: Build Electron App
      run: npm run build

    - name: Package App into DMG
      run: |
        npm install electron-packager -g
        electron-packager . Pixelmate --platform=darwin --arch=x64 --overwrite --icon=public/app.icns
        npm install electron-installer-dmg -g
        electron-installer-dmg Pixelmate-darwin-x64/Pixelmate.app Pixelmate

    - name: Upload DMG to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Pixelmate.dmg
        path: Pixelmate.dmg
